// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'en';

export type Locales = 'en' | 'pt';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
	/**
	 * C​r​e​a​t​e​ ​c​o​n​t​a​c​t​s​ ​l​i​s​t
	 */
	createList: string;
	/**
	 * N​e​w
	 */
	new: string;
};

export type TranslationFunctions = {
	/**
	 * Create contacts list
	 */
	createList: () => LocalizedString;
	/**
	 * New
	 */
	new: () => LocalizedString;
};

export type Formatters = {};
